apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - name: tcp-3306
    targetPort: 3306
    protocol: TCP
    port: 3306
    nodePort: 30306 #暴露端口
  selector:
    app: mysql
  type: NodePort

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi  #设置 pv 存储资源大小 
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/Users/knight/Documents/k8s/mysql/data/"
    type: DirectoryOrCreate # 如果路径不存在，则创建该目录
---
#持久声明
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: mysql-pv-volume # 确保PVC与PV关联
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:9.1
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456" # 设置你的root密码
          - name: MYSQL_DATABASE
            value: "k8s_mysql" # 创建一个新的数据库
          - name: MYSQL_USER
            value: "k8s_user" # 创建一个新的用户
          - name: MYSQL_PASSWORD
            value: "123456" # 设置新用户的密码
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim