apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - name: tcp-6379
    targetPort: 6379
    protocol: TCP
    port: 6379
    nodePort: 32637 #暴露端口
  selector:
    app: redis
  type: NodePort

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi  #设置 pv 存储资源大小 
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/Users/knight/Documents/k8s/redis/data/"
    type: DirectoryOrCreate # 如果路径不存在，则创建该目录
---
#持久声明
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: redis-pv # 确保PVC与PV关联
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:6.2.6
        name: redis
        command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
        env:
          - name: REDIS_PASSWORD
            value: "123456"
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc