{
 "title": "Game Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "project_name",
    "label": "project_name",
    "query": {
     "query": "label_values(queued_players{project_name=\"ggd\"},project_name)"
    }
   },
   {
    "name": "zone_id",
    "query": {
     "query": "label_values(queued_players{project_name=\"ggd\"},zone_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "OverView", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avatar 总在线人数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(online_players{project_name=\"$project_name\", zone_id=\"$zone_id\",server_type=\"avatar\"}) OR sum(avatar_online_players{project_name=\"$project_name\", zone_id=\"$zone_id\"})",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "World 总在线人数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(online_players{project_name=\"$project_name\", zone_id=\"$zone_id\", server_type=\"world\"}) OR sum(world_online_players{project_name=\"$project_name\", zone_id=\"$zone_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "大区总排队人数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(queued_players{project_name=\"$project_name\", zone_id=\"$zone_id\"})",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  { "title": "在线人数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "大区在线人数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(online_players{project_name=\"${project_name}\", zone_id=\"$zone_id\", server_type=\"avatar\"}) OR sum(avatar_online_players{project_name=\"${project_name}\", zone_id=\"$zone_id\"})",
     "legendFormat": "Avatar"
    },
    {
     "expr": "sum(online_players{project_name=\"${project_name}\", zone_id=\"$zone_id\", server_type=\"world\"}) OR sum(world_online_players{project_name=\"${project_name}\", zone_id=\"$zone_id\"})",
     "legendFormat": "World"
    }
   ]
  },
  {
   "title": "全区总排队人数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "max(queued_players{project_name=\"$project_name\", zone_id=\"$zone_id\"})",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Avatar 单服务器在线人数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (server_name) (online_players{project_name=\"${project_name}\", zone_id=\"$zone_id\", server_type=\"avatar\"}) OR sum by (server_name) (avatar_online_players{project_name=\"${project_name}\", zone_id=\"$zone_id\"})",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "World 单服务器在线人数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (server_name) (online_players{project_name=\"${project_name}\", zone_id=\"$zone_id\", server_type=\"world\"}) OR sum by (server_name) (world_online_players{project_name=\"${project_name}\", zone_id=\"$zone_id\"})",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  { "title": "登录", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "登录 API 失败率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_min(sum(rate(http_server_requests_code_total{project_name=\"$project_name\", zone_id=\"$zone_id\", server_type=\"account\", path=\"/Account/Login\", code!=\"200\"}[$__rate_interval])), 0) / clamp_min(sum(rate(http_server_requests_code_total{project_name=\"$project_name\", zone_id=\"$zone_id\", server_type=\"account\", path=\"/Account/Login\"}[$__rate_interval])), 1) * 100 or vector(0)",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "登录 API 响应延迟（ms）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "clamp_min(sum by(path_name) (rate(http_server_requests_duration_ms_sum{project_name=\"$project_name\", zone_id=\"$zone_id\", server_type=\"account\", path=\"/Account/Login\"}[$__rate_interval])), 0) / clamp_min(sum by(path_name) (rate(http_server_requests_duration_ms_count{project_name=\"$project_name\", zone_id=\"$zone_id\", server_type=\"account\", path=\"/Account/Login\"}[$__rate_interval])), 1)",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "场景人数",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "各场景在线人数",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum by (map_name) (scene_online_players{project_name=\"$project_name\", zone_id=\"$zone_id\"})",
       "legendFormat": "map_name: {{map_name}}"
      }
     ]
    }
   ]
  },
  { "title": "帧率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Tick 响应延迟（ms）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "clamp_min(sum by(server_name, type) (rate(frame_fps_sum{project_name=\"$project_name\", zone_id=\"$zone_id\", type=\"tick\"}[$__rate_interval])), 0) / clamp_min(sum by(server_name, type) (rate(frame_fps_count{project_name=\"$project_name\", zone_id=\"$zone_id\",  type=\"tick\"}[$__rate_interval])), 1)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  { "title": "消息(服务端）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "消息响应延迟（ms）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "clamp_min(sum by(api_name) (rate(message_response_delay_ms_sum{project_name=\"$project_name\", zone_id=\"$zone_id\"}[$__rate_interval])), 0) / clamp_min(sum by(api_name) (rate(message_response_delay_ms_count{project_name=\"$project_name\", zone_id=\"$zone_id\"}[$__rate_interval])), 1)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "Avatar 消息数量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 47 },
   "targets": [
    {
     "expr": "sum by(api_name, server_type) (rate(message_count_total{project_name=\"$project_name\", zone_id=\"$zone_id\", server_type=\"avatar\"}[$__rate_interval]))",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "World 消息数量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "expr": "sum by(api_name, server_type) (rate(message_count_total{project_name=\"$project_name\", zone_id=\"$zone_id\", server_type=\"world\"}[$__rate_interval]))",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  { "title": "消息(压测环境)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "消息成功率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(api_name) (rate(message_transaction_total{project_name=\"$project_name\", job=\"performance-test\", code=\"0\"}[$__rate_interval])) / sum by(api_name) (rate(message_transaction_total{project_name=\"$project_name\",job=\"performance-test\"}[$__rate_interval])) * 100",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "消息响应延迟（ms）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "clamp_min(sum by(api_name) (rate(message_response_delay_ms_sum{project_name=\"$project_name\",job=\"performance-test\"}[$__rate_interval])), 0) / clamp_min(sum by(api_name) (rate(message_response_delay_ms_count{project_name=\"$project_name\",job=\"performance-test\"}[$__rate_interval])), 1)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "消息数量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "sum by(api_name, server_type) (rate(message_count_total{project_name=\"$project_name\", job=\"performance-test\"}[$__rate_interval]))",
     "legendFormat": "{{api_name}}"
    }
   ]
  }
 ]
}