{
 "title": "NATS Servers",
 "description": "NATS Server Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "project_name",
    "label": "project_name",
    "query": {
     "query": "label_values(gnatsd_varz_cpu{project_name=\"ggd\"},project_name)"
    }
   },
   {
    "name": "zone_id",
    "label": "zone_id",
    "query": {
     "query": "label_values(gnatsd_varz_cpu{project_name=\"$project_name\"},zone_id)"
    }
   },
   {
    "name": "server_type",
    "label": "server_type",
    "query": {
     "query": "label_values(gnatsd_varz_cpu{project_name=\"$project_name\",zone_id=\"$zone_id\"},server_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnatsd_healthz_status{zone_id=\"${zone_id}\",project_name=\"${project_name}\",server_type=\"${server_type}\"}",
     "legendFormat": "{{ server_id }}"
    }
   ]
  },
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gnatsd_varz_cpu{zone_id=\"${zone_id}\",project_name=\"${project_name}\",server_type=\"${server_type}\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gnatsd_varz_mem{zone_id=\"${zone_id}\",project_name=\"${project_name}\",server_type=\"${server_type}\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(gnatsd_varz_in_bytes{zone_id=\"${zone_id}\",project_name=\"${project_name}\",server_type=\"${server_type}\"}[$__rate_interval])*8",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "NATS Msgs In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(gnatsd_varz_in_msgs{zone_id=\"${zone_id}\",project_name=\"${project_name}\",server_type=\"${server_type}\"}[$__rate_interval])",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(gnatsd_varz_out_bytes{zone_id=\"${zone_id}\",project_name=\"${project_name}\",server_type=\"${server_type}\"}[$__rate_interval])*8",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "NATS Msgs Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(gnatsd_varz_out_msgs{zone_id=\"${zone_id}\",project_name=\"${project_name}\",server_type=\"${server_type}\"}[$__rate_interval])",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gnatsd_varz_connections{zone_id=\"${zone_id}\",project_name=\"${project_name}\",server_type=\"${server_type}\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gnatsd_varz_subscriptions{zone_id=\"${zone_id}\",project_name=\"${project_name}\",server_type=\"${server_type}\"}",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(gnatsd_varz_slow_consumers{zone_id=\"${zone_id}\",project_name=\"${project_name}\",server_type=\"${server_type}\"}[$__rate_interval])",
     "legendFormat": "{{server_id}}"
    }
   ]
  }
 ]
}