apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-mongodb
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.type }}
  selector:
    app: mongodb
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.mongodb.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "chart.fullname" . }}-mongodb-pv-volume
  labels:
    type: local
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /run/desktop/mnt/host/d/k8s/data/mongodb
    type: DirectoryOrCreate
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-mongodb-pv-claim
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mongodbPvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.mongodbPvClaim.storageClass | quote }}
  volumeName: mongodb-pv-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-mongodb
  labels:
    app: mongodb
  {{- include "chart.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.mongodb.strategy.type | quote }}
  selector:
    matchLabels:
      app: mongodb
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mongodb
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ quote .Values.mongodb.mongodb.env.mongoInitdbRootUsername }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ quote .Values.mongodb.mongodb.env.mongoInitdbRootPassword }}
        - name: MONGO_INITDB_DATABASE
          value: {{ quote .Values.mongodb.mongodb.env.mongoInitdbDatabase }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mongodb.mongodb.image.repository }}:{{ .Values.mongodb.mongodb.image.tag
          | default .Chart.AppVersion }}
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-persistent-storage
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "chart.fullname" . }}-mongodb-pv-claim
