apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-mysql
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.type }}
  selector:
    app: mysql
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.mysql.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "chart.fullname" . }}-mysql-pv-volume
  labels:
    type: local
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /run/desktop/mnt/host/d/k8s/data/mysql
    type: DirectoryOrCreate
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-mysql-pv-claim
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mysqlPvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.mysqlPvClaim.storageClass | quote }}
  volumeName: mysql-pv-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-mysql
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.mysql.strategy.type | quote }}
  selector:
    matchLabels:
      app: mysql
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mysql
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ quote .Values.mysql.mysql.env.mysqlRootPassword }}
        - name: MYSQL_DATABASE
          value: {{ quote .Values.mysql.mysql.env.mysqlDatabase }}
        - name: MYSQL_USER
          value: {{ quote .Values.mysql.mysql.env.mysqlUser }}
        - name: MYSQL_PASSWORD
          value: {{ quote .Values.mysql.mysql.env.mysqlPassword }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mysql.mysql.image.repository }}:{{ .Values.mysql.mysql.image.tag
          | default .Chart.AppVersion }}
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "chart.fullname" . }}-mysql-pv-claim
