apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-redis
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.type }}
  selector:
    app: redis
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.redis.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "chart.fullname" . }}-pv
  labels:
    type: local
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /run/desktop/mnt/host/d/k8s/data/redis
    type: DirectoryOrCreate
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-pvc
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.pvc.storageClass | quote }}
  volumeName: redis-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-redis
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.redis.strategy.type | quote }}
  selector:
    matchLabels:
      app: redis
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: redis
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
        env:
        - name: REDIS_PASSWORD
          value: {{ quote .Values.redis.redis.env.redisPassword }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.redis.redis.image.repository }}:{{ .Values.redis.redis.image.tag
          | default .Chart.AppVersion }}
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-storage
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: {{ include "chart.fullname" . }}-pvc
