apiVersion: v1
kind: Namespace
metadata:
  name: deploy-env
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: deploy-env
spec:
  ports:
  - name: tcp-27017
    targetPort: 27017
    protocol: TCP
    port: 27017
    nodePort: 32717 #暴露端口
  selector:
    app: mongodb
  type: NodePort

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-volume
  namespace: deploy-env
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi  #設置 pv 存儲資源大小 
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /run/desktop/mnt/host/d/k8s/data/mongodb #windows:  /run/desktop/mnt/host/ + 实际路径
    type: DirectoryOrCreate # 如果路徑不存在，則創建該目錄
---
#持久聲明
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  namespace: deploy-env
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: mongodb-pv-volume # 確保PVC與PV關聯
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: deploy-env
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:6.0
        name: mongodb
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "root123"
          - name: MONGO_INITDB_DATABASE
            value: "k8s_mongodb"
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
