apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
      nodePort: 30022  # 本地可以通过这个端口访问 NATS
    - name: cluster
      port: 6222
      targetPort: 6222
    - name: monitoring
      port: 8222
      targetPort: 8222
      nodePort: 30082  # 本地可以通过这个端口查看 NATS 监控界面

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.10.11
          ports:
            - containerPort: 4222
            - containerPort: 6222
            - containerPort: 8222
          args: [
            "-m", "8222"
          ]

---
apiVersion: v1
kind: Service
metadata:
  name: nats-exporter
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: nats-exporter
  ports:
    - name: metrics
      port: 7777
      targetPort: 7777
      nodePort: 30077
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-exporter
  template:
    metadata:
      labels:
        app: nats-exporter
    spec:
      containers:
        - name: nats-exporter
          image: natsio/prometheus-nats-exporter:0.15.0
          ports:
            - containerPort: 7777
          command: [
            "/entrypoint.sh",
            "--varz",
            "--connz",
            "--routez",
            "--serverz",
            "--subz",
            "http://nats.monitoring.svc.cluster.local:8222",
          ]