apiVersion: v1
kind: Namespace
metadata:
  name: deploy-env
---
apiVersion: v1
kind: Service
metadata:
  name: redis8
  namespace: deploy-env
spec:
  ports:
  - name: tcp-6379
    targetPort: 6379
    protocol: TCP
    port: 6379
    nodePort: 32638 # 与 redis6 区分
  selector:
    app: redis8
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis8-pv
  namespace: deploy-env
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /run/desktop/mnt/host/d/k8s/data/redis8  # 换成 redis8 独立目录
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis8-pvc
  namespace: deploy-env
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: redis8-pv
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis8
  namespace: deploy-env
spec:
  selector:
    matchLabels:
      app: redis8
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis8
    spec:
      containers:
      - image: redis:8.2
        name: redis8
        command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
        env:
          - name: REDIS_PASSWORD
            value: "123456"
        ports:
        - containerPort: 6379
          name: redis8
        volumeMounts:
        - name: redis8-storage
          mountPath: /data
      volumes:
      - name: redis8-storage
        persistentVolumeClaim:
          claimName: redis8-pvc
